# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
  
  
title: 'Incoherent thinking'
description: "Ramblings about computers, games and people acting irresponsibly"
url: "https://www.guestnone.me"

style: dark

header_pages:
  - index.md
  - about.md

site_author: Patrick Rećko
content_license: CC-BY 4.0

markdown: kramdown